### PR TITLE
Rewrite xml literals to interpolator

### PR DESCRIPTION
**Pull request by allanrenucci**
I am writing an xml interpolator and a scalafix rewrite.

The purpose of this PR is to make sure the tests still pass without choking my cpu.

### CODE REVIEW

**Comment by Shadowfiend** [comment]
Heads up: Travis may be failing for reasons due to their recent environment update. I noticed this yesterday but didn't get a chance to fix it.

**Comment by Shadowfiend** [comment]
Going to try closing/reopening so travis can do a fresh merged build with the build config fixes.

**Comment by allanrenucci** [comment]
@Shadowfiend Thanks!

**Comment by Shadowfiend** [comment]
Looks like that failed in Scala 2.11 but passed in Scala 2.12!

**Comment by allanrenucci** [comment]
Wow I rebased and it fixed the issue. Strange...

**Comment by Shadowfiend** [comment]
This does seem odd, but I suspect this may be due to the way that travis/github were computing the auto-merge commit that the tests were running against. I've occasionally seen strangeness like this before with an automatic merge that did not manifest after a rebase or manual merge.

So……… AWESOME! :)

**Comment by farmdawgnation** [comment]
This is a simple travis change so I'm going to ship it!

**Comment by Shadowfiend** [comment]
Wait… Was this a simple travis change? @allanrenucci I feel like it wasn't meant to be, so maybe the rebase lost the actual XML literal change…

**Comment by allanrenucci** [comment]
Ooops! Indeed I got rid of the xml change somehow...

**Comment by Shadowfiend** [comment]
Haha well thanks for bumping our Scala versions! :) Feel free to open another PR to test the real changes if you'd like.

**Pull request merged**
