### PR TITLE
Use proper method to check snippet existence in the snippetClassMap

### PR DESCRIPTION
**Pull request by mroocoo**
"contains" searches by value not by key - "containsKey" should be used

### CODE REVIEW

**Comment by farmdawgnation** [comment]
Hey @mroocoo thanks for the contribution!

Was there a discussion about this on our mailing list somewhere? I haven't looked at these changes in depth yet, but having some sort of description of the behavior you were seeing that caused you to want to change this would be super helpful for review. =)

**Comment by mroocoo** [comment]
Hi, i don&#39;t know if there is any discussion about this. Some time ago i&#39;ve noticed that snippet classes was unnecessarily searched each time when rendered and as there were many classes in my project it was slow. I made this small change on my local branch and this fixed my issue. And as you look at the code other methods of snippetClassMap (&#39;putIfAbsent&#39;, &#39;get&#39;) access this map by key, but &#39;contains&#39; do not. With the &#39;contains&#39; method the snippet class cache does not work at all and searches classes each time when invoked.  Dnia 12 kwietnia 2017 15:49 Matt Farmer &lt;notifications@github.com&gt; napisał(a):  Hey  github.com @mroocoo  thanks for the contribution!  Was there a discussion about this on our mailing list somewhere? I haven&#39;t looked at these changes in depth yet, but having some sort of description of the behavior you were seeing that caused you to want to change this would be super helpful for review. =)  —  You are receiving this because you were mentioned.  Reply to this email directly,  github.com view it on GitHub , or  github.com mute the thread .

**Comment by farmdawgnation** [comment]
Got it.

Per our contributing guidelines we typically like to have a discussion on the mailing list to validate that there's not some unexpected edge case as a result of this, but given that this is a fairly straightforward change and _looks_ pretty uncontroversial I think we can waive that requirement.

I'll try to make some time tomorrow to test and grok this, unless someone gets to it before me.

**Comment by farmdawgnation** [comment]
@mroocoo Please add your name and email to the contributors file at the root of the project so this meets that requirement of our contribution guidelines.

**Comment by Shadowfiend** [comment]
Upon closer look, this is probably an artifact of the switch from Scala concurrent maps to the Java `ConcurrentHashMap`. Sadly wasn't flagged by the compiler.

Thanks for the contribution!

**Comment by farmdawgnation** [comment]
These changes are approved. Thank you again @mroocoo, this will ship as a part of Lift 3.1.0-M3 on or around the first of June!

**Pull request merged**
