### PR TITLE
Travis Integration

### PR DESCRIPTION
**Pull request by Shadowfiend**
Based off of #1662, but in one of our branches so I can mess with it ;)

### CODE REVIEW

**Comment by Shadowfiend** [comment]
Now that I look at it it looks like Travis will build the branch without a PR, so that's pretty handily-dandily handy-dandy…

**Comment by arkadius** [comment]
Maybe it is a reason why: "Travis CI builds a pull request when it's first opened and when commits are added to the pull request throughout its lifetime.". I see that #1666 and #1603 is checked agains build. Because of #1661 they are failed. However discussion about TimeSpan problem fix doesn't involve too many persons on mailing list.

**Comment by Shadowfiend** [comment]
Yeah, we'll see. I'm going to follow up on the TimeSpan discussion today if I get a chance.

**Comment by Shadowfiend** [comment]
Okay okay okay, these now seem to be passing; cleaned up history a bit, will merge it in once travis gives the green light.

**Pull request merged**
