### PR TITLE
Session IPA: Split out SessionMaster and ScopedLiftActor from LiftSession

### PR DESCRIPTION
**Pull request by farmdawgnation**
session ipa

My eyes were bigger than my stomach in #1641 – the changes that are going to be required to do that properly are going to require a lot of discussion on the list so for now I say we consider that ticket closed after this PR is merged and kick of a discussion sometime in the future about how to look at LiftSession again. For this one, there were two things in LiftSession that were relatively easy to move:

- SessionMaster because it is sufficiently complex imo to warrant its own file.
- ScopedLiftActor because it's apparently not used anywhere in session management period. It's just kind of there, and warrants its own file just by being not fundamentally related to LiftSession.

### CODE REVIEW

**Comment by Shadowfiend** [comment]
These look like straight copy-paste jobs, no extraneous changes, right?

**Comment by Shadowfiend** [comment]
(If so, I'm :+1: !)

**Comment by farmdawgnation** [comment]
That's correct.

**Comment by fmpwizard** [comment]
I think I know the answer (no) but is there a way that we could keep the history of those two new files?, as it stands on this PR, it will look as if the code for those two files started on this PR

**Comment by Shadowfiend** [comment]
I don't think there's a way to keep traceability, no, though the individual lines of code may well be traceable through file changes.

**Comment by fmpwizard** [comment]
tnx, alright, :+1:  from me too so merging in ...

**Pull request merged**
