### PR TITLE
Fixed missing `s` in string interpolation

### PR DESCRIPTION
**Pull request by fmpwizard**
as discussed here
https://groups.google.com/d/topic/liftweb/jjV3vFhIReA/discussion

### CODE REVIEW

**Comment by farmdawgnation** [comment]
This looks :+1: but openjdk doesn't look happy. But that's an issue on Travis isn't it?

**Comment by fmpwizard** [comment]
looking at the travis log, I see it could not find:
org.scala-lang#scala-compiler;2.10.4!scala-compiler.jar


and it's weird how here it shows fail, but I got an email from travis saying  : 

**Passed: lift/framework#60 (diego_issue_string_inter - dc632a9)**

**Comment by Shadowfiend** [comment]
Yeah, so travis runs builds both on branch push and on PR open I believe. So you probably got a successful run of the branch push and a failed run on the PR.

I've seen that scala compiler resolution issue before… Not sure why we're even depending on the scala 2.10.4 compiler JAR—presumably there's a transitive dependency somewhere. The OpenJDK build seems a little questionable in general; it's also hung for >10 minutes causing travis to kill the build due to lack of activity. May be worth discussing turning it off unless/until someone is willing to give it some attention.

**Comment by fmpwizard** [comment]
the scala compiler 2.10.4 is the one sbt 0.13 needs :(
ok, merging this ...

**Pull request merged**
