### PR TITLE
12 Happy Folk: Add 2.12 to the Lift cross-compile

### PR DESCRIPTION
**Pull request by Shadowfiend**
Pulling in changes from #1812, trying to get a successful 2.12 build.

### CODE REVIEW

**Comment by Shadowfiend** [comment]
So right now it looks like we're actually crashing the compiler in lift-actor...:

```
java.lang.ArrayIndexOutOfBoundsException: -1
	at scala.tools.nsc.backend.jvm.analysis.BackendUtils.enqInsnIndex$1(BackendUtils.scala:430)
	at scala.tools.nsc.backend.jvm.analysis.BackendUtils.enqInsn$1(BackendUtils.scala:426)
	at scala.tools.nsc.backend.jvm.analysis.BackendUtils.computeMaxLocalsMaxStack(BackendUtils.scala:477)
	at scala.tools.nsc.backend.jvm.analysis.BackendUtils$AsmAnalyzer.<init>(BackendUtils.scala:35)
	at scala.tools.nsc.backend.jvm.opt.LocalOpt.removeUnreachableCodeImpl(LocalOpt.scala:488)
	at scala.tools.nsc.backend.jvm.opt.LocalOpt.removalRound$2(LocalOpt.scala:275)
	at scala.tools.nsc.backend.jvm.opt.LocalOpt.methodOptimizations(LocalOpt.scala:354)
	at scala.tools.nsc.backend.jvm.opt.LocalOpt.$anonfun$methodOptimizations$1(LocalOpt.scala:195)
	at scala.tools.nsc.backend.jvm.opt.LocalOpt.$anonfun$methodOptimizations$1$adapted(LocalOpt.scala:194)
	at scala.tools.nsc.backend.jvm.opt.LocalOpt$$Lambda$1582/531469953.apply(Unknown Source)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce$$Lambda$93/773059045.apply(Unknown Source)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:932)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at scala.tools.nsc.backend.jvm.opt.LocalOpt.methodOptimizations(LocalOpt.scala:194)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase$Worker2.$anonfun$localOptimizations$1(GenBCode.scala:248)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase$Worker2.localOptimizations(GenBCode.scala:248)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase$Worker2.run(GenBCode.scala:267)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.buildAndSendToDisk(GenBCode.scala:384)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.run(GenBCode.scala:350)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1404)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1389)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1384)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1478)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:51)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:51)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:51)
	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:75)
	at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:65)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:31)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:62)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:61)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:89)
	at sbt.inc.Incremental$.compile(Incremental.scala:61)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
	at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
	at sbt.Compiler$.compile(Compiler.scala:128)
	at sbt.Compiler$.compile(Compiler.scala:114)
	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:814)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:805)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:803)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] Error while emitting net/liftweb/actor/SpecializedLiftActor
[error] -1
[error] one error found
```

Will see what I can dig up.

**Comment by Shadowfiend** [comment]
Looks like @marekzebrowski ran into this about a week ago and reported it [to the scala-internals list](https://groups.google.com/forum/#!topic/scala-internals/ixmajCw9nfg) and on [the Scala bug tracker](https://issues.scala-lang.org/browse/SI-10032).

**Comment by Shadowfiend** [comment]
Did some more digging here by changing the offending code so we'd at least get through compile. Biggest issue it looks like is with the Squeryl 0.9.7 dependency (bumped from 0.9.5-7 because that's not build for 2.12). Big compile explosion in squeryl-record there:

```
[error] /Users/shadowfiend/github/framework-prs/persistence/squeryl-record/src/main/scala/net/liftweb/squerylrecord/RecordTypeMode.scala:22: object ConstantExpressionNode is not a member of package org.squeryl.dsl.ast
[error] import org.squeryl.dsl.ast.{ SelectElementReference, SelectElement, ConstantExpressionNode, RightHandSideOfIn }
[error]        ^
[error] /Users/shadowfiend/github/framework-prs/persistence/squeryl-record/src/main/scala/net/liftweb/squerylrecord/RecordTypeMode.scala:179: wrong number of type arguments for org.squeryl.dsl.ast.SelectElementReference, should be 2
[error]       new SelectElementReference[Enumeration#Value](e)(e.createEnumerationMapper(reifySingleton(m).values.iterator.next)) with EnumExpression[Enumeration#Value] with SquerylRecordNonNumericalExpression[Enumeration#Value]
[error]           ^
[error] /Users/shadowfiend/github/framework-prs/persistence/squeryl-record/src/main/scala/net/liftweb/squerylrecord/RecordTypeMode.scala:21: object BooleanExpression is not a member of package org.squeryl.dsl
[error] import org.squeryl.dsl.{ BooleanExpression, DateExpression, EnumExpression, NumericalExpression, StringExpression, NonNumericalExpression }
[error]        ^
```

This then cascades down. Any thoughts @pbrant or @eltimn (I think y'all interact with Squeryl most)?

**Comment by marekzebrowski** [comment]
Exactly. but fortunately bug is fixed for upcoming 2.12.1

**Comment by Shadowfiend** [comment]
Yep! I updated my original comment to link to the thread, the issue, the fix, and the expected release date for 2.12.1. Thanks for sleuthing this before we got to it and reporting it!

**Comment by Shadowfiend** [comment]
Just pushed a bunch of additional fixes and tweaks for 2.12 support. I commented out the part of `LiftActor` that breaks the 2.12.0 compile, but that part is pretty critical to actors being thread-safe, so that's not in this push; instead, this fixes all other issues besides squeryl.

**Comment by xuwei-k** [comment]
> Biggest issue it looks like is with the Squeryl 0.9.7 dependency (bumped from 0.9.5-7 because that's not built for 2.12). 

I just published sqeuryl 0.9.5-7 for Scala 2.12
https://oss.sonatype.org/content/repositories/releases/org/squeryl/squeryl_2.12/0.9.5-7/

**Comment by Shadowfiend** [comment]
@xuwei-k that is *tremendously* kind of you, thank you so much!

**Comment by bchazalet** [comment]
[2.12.1 ](http://www.scala-lang.org/news/2.12.1) has been published :)

**Comment by Shadowfiend** [comment]
Yep, saw that yesterday. Will be spinning up a 3.0 build for it when I get a chance.

**Comment by Shadowfiend** [comment]
Ok, looks like things are working here; I've removed the WIP tag from the PR.

@fmpwizard if this looks good to you, what do you think about publishing a 2.12 build for 3.0 from this branch? It should contain all of the 3.0 commits + only the ones to get 2.12 going.

**Comment by farmdawgnation** [comment]
This may just me picking a nit, but that kind of sounds like a 3.0.1, to me. :wink:

**Comment by Shadowfiend** [comment]
That's actually a good point, as the dependencies have changed. Perhaps a 3.0.1 build for both 2.11 and 2.12?

**Comment by fmpwizard** [comment]
@Shadowfiend @farmdawgnation +1 on getting this to master and then I can build a 3.0.1 that cross compiles 2.11 and 2.12

And speaking of 3.0.1, iirc there was a thread about adopting SemVer, but cannot find it, was it finally decided or do we keep the usual 3.1 format?

**Comment by Shadowfiend** [comment]
Not sure that we made a final decision---I've mostly been speaking in semver, though. Don't feel super-strongly about explicitly saying “3.1.0” vs “3.1”, but it would be nice.

Re: getting it on master---this branch'll be easier to build, as master is already tracking 3.1 and has a few PR merges. We can either tag the HEAD of this branch for 3.0.1, or I can create a new lift-3.0 branch for updates to 3.0 while 3.1 goes out the door, and cherry-pick these commits over there. Let me know which you prefer!

**Comment by fmpwizard** [comment]
re: master, it would be great if you could create a lift-3.0 with these changes, in case we have to do another minor 3.0 build.

re: semver, I'll send an email to the regular list

**Comment by Shadowfiend** [comment]
Cool, I'll get it!

**Comment by Shadowfiend** [comment]
Added a [`lift-3.0` branch](https://github.com/lift/framework/tree/lift-3.0). Currently the version there is 3.0.1-SNAPSHOT, so that you can bump it to 3.0.1 when you do the build.

Once that's done I think someone can also merge this PR :tada:

**Comment by Shadowfiend** [comment]
@fmpwizard Do you have time to do this in the next few days? If not I'm happy to pick it up (pretty sure I have publish rights to lift on sonatype).

**Comment by fmpwizard** [comment]
Should be able to do this tonight or tomorrow night

Diego

**Comment by Shadowfiend** [comment]
💞

**Comment by fmpwizard** [comment]
I just tried to published 3.0.1 but run into this bug:

https://github.com/scala/scala-dev/issues/249

I'm going to use the workaround, but hope they fix it soon, 

```
sbt:lift-framework:3.0.1> project lift-actor
[info] Set current project to Lift Actor (in build file:/home/diego/work/lift/framework/)
sbt:lift-actor:3.0.1> compile
[warn] Credentials file /home/diego/.sbt/0.13/.credentials does not exist
[warn] Credentials file /home/diego/.sbt/0.13/.credentials does not exist
[success] Total time: 0 s, completed Dec 12, 2016 11:04:27 PM
sbt:lift-actor:3.0.1> compile:doc
[warn] Credentials file /home/diego/.sbt/0.13/.credentials does not exist
[warn] Credentials file /home/diego/.sbt/0.13/.credentials does not exist
[info] Main Scala API documentation to /home/diego/work/lift/framework/core/actor/target/scala-2.12/api...
[error] /home/diego/work/lift/framework/core/actor/src/main/java/net/liftweb/actor/JavaActorBase.java:16: inner classes cannot be classfile annotations
[error]     public @interface Receive {
[error]                       ^
[info] No documentation generated with unsuccessful compiler run
[error] one error found
[error] (lift-actor/compile:doc) Scaladoc generation failed
[error] Total time: 6 s, completed Dec 12, 2016 11:04:41 PM
sbt:lift-actor:3.0.1> set scalacOptions in (Compile, doc) += "-no-java-comments"
[info] Defining lift-actor/compile:doc::scalacOptions
[info] The new value will be used by lift-actor/compile:doc
[info] Reapplying settings...
   ___,__      _     _   __  _                    
  |  / \  \   | |   (_)/  _|| |_    Lift Framework
  |  | |  |   | |__ | ||  _||  _|   3.0.1 for Scala 2.12.1
   \__\_\_.   |____||_||_|   \__|   

[info] Set current project to Lift Actor (in build file:/home/diego/work/lift/framework/)
sbt:lift-actor:3.0.1> compile:doc
[warn] Credentials file /home/diego/.sbt/0.13/.credentials does not exist
[warn] Credentials file /home/diego/.sbt/0.13/.credentials does not exist
[info] Main Scala API documentation to /home/diego/work/lift/framework/core/actor/target/scala-2.12/api...
model contains 21 documentable templates
[info] Main Scala API documentation successful.
[success] Total time: 4 s, completed Dec 12, 2016 11:05:20 PM
sbt:lift-actor:3.0.1> 

```

**Comment by Shadowfiend** [comment]
Merging as 3.0.1 is on sonatype now. Release notes for 3.0.1 to come.

**Comment by bchazalet** [comment]
Thank you so much guys!

**Pull request merged**
