### PR TITLE
Fixed the new bind-less password change in ProtoUser

### PR DESCRIPTION
**Pull request by dpp**
Fixed an issue with the way CSS Selectors work so that password change in ProtoUser works again.

### CODE REVIEW

**Comment by Shadowfiend** [comment]
Just to check here, the issue at hand was that the CSS bind will bind two separate password inputs that will each receive one value, instead of creating one password input bound in two places, right?

**Comment by dpp** [comment]
Yep... 2 different functions, 2 different values... neither sets the right thing in the duplicate password in the User

**Comment by Shadowfiend** [comment]
Yep, I've been bitten by the laziness of CSS selector binds like this before… Obviously I haven't learned my lesson yet :disappointed: 

:+1: on the change, let's get it in.

**Comment by hedefalk** [comment]
Ah, got it! Thanks!

And sorry for taking your time, I just _hate_ to drop it when I don't understand something…

**Comment by Shadowfiend** [comment]
As well it should be :)

**Pull request merged**
