### PR TITLE
Comet Collision: Initial comet cleanup

### PR DESCRIPTION
**Pull request by Shadowfiend**
Bunch of changes here, but mostly it’s rearrangement and documentation
work. `MessageCometActor` was renamed to `MessagingCometActor` in preparation
for the reworking of how `CometActor` is actually split up (into messaging and
then rendering layered on top of it).

Also split out a couple of distinct chunks into their own files (`ListenerManager`
and `StatefulComet`).

Merge is going to an integration branch; figured it would make it easier to
handle reviewing the actual changes to the structure of CometActor.

### CODE REVIEW

**Comment by Shadowfiend** [comment]
Whoops, this is probably going to blow up; forgot to do compilation checks to make sure all my imports were in order >_>

**Comment by pbrant** [comment]
Looks good to me. +1

**Comment by Shadowfiend** [comment]
If travis signs off on the compilation fix I just pushed, I'm going to go ahead and merge this as I continue work on the rest.

**Comment by Shadowfiend** [comment]
Looks like some concurrency issues in `LAFutureSpecs` on `master`, but unrelated to this branch, so in we go.

**Pull request merged**
