### PR TITLE
travis integration

### PR DESCRIPTION
**Pull request by arkadius**
- build script
- build status in README

Jus sign in with github account, turn on project, additional turn on "Build only if .travis.yml is present" and send some triggering commit. You can also reconfigure notifications in .travis.yml if you prefer according to: http://docs.travis-ci.com/user/notifications/

discusiion link: https://groups.google.com/forum/#!topic/liftweb/hHzK9lgXyKs

### CODE REVIEW

**Comment by karma4u101** [comment]
Thanks for the pull request 
So (just to clarify) sign in to https://travis-ci.org/ with the "lift" github account and then chose the repository tab (on the account page) and enable the lift/framwork repo "sync".

The pull looks good to me but maybe you should update the yml file a bit and add the language line(?) and maybe also the Scala version or have you omitted the version on purpose as the script will make travis pick up the right one?
For Lift 3.0 we only build using 2.11.x so no need for several version builds but maybe adding openjdk7 to the jdk section would be good.   

language: scala
scala:
  - "2.11.2"
services:
  - mongodb
jdk:
  - openjdk7
  - oraclejdk7
script: ./liftsh test

**Comment by arkadius** [comment]
Yes, exactly.

Changes proposed by you will not break the build but as far as I understand travis build process, they aren't necessary. Line 'script: ./liftsh test' mean that all what travis will do is to run the script. If it return 0 error code, build is fine otherwise fails.

All additional settings are in your lift.sh and sbt settings.

If you want I might add proposed changes.

BTW you can use apostrophes for mark a code sections

**Comment by karma4u101** [comment]
I thought the language line was necessary but i recon you have already run it without specifying it so that's probably fine and if the script makes travis pick the right Scala version that's fine two then the only extra thing would be to add openjdk7 but I guess that's such a minor thing it could be done afterwards if needed. 

I think it needs to be the lift account, I am a commiter but the lift/framwork repository is not available on the repository tab. 
I did find the apostrophes ;)

**Comment by arkadius** [comment]
Yes, I've tested this configuration on my fork.

I've just added openjdk7 profile. It will be a good choice to test build on more environments in future :)

**Comment by karma4u101** [comment]
Great, then from my view this is looking good but I will leave this pull open until someone with account rights have time to take a look at this. 
Thanks

**Comment by arkadius** [comment]
Ok, tkanks for review!
Arek
5 sty 2015 23:47 "Peter Petersson" <notifications@github.com> napisał(a):

**Comment by Shadowfiend** [comment]
Lemme get my hands dirty :)

**Comment by Shadowfiend** [comment]
I don't see a particular benefit to putting the build status in the README—successful builds will be deployed as `-SNAPSHOT` versions, successful PRs will be visible in the PRs, and successful version releases will be deployed under their version artifacts. Am I forgetting something or does this seem reasonable?

**Comment by Shadowfiend** [comment]
(Worth mentioning—we won't be able to replace cloudbees completely until we can get travis deploying successful builds to `-SNAPSHOT`, but nothing's preventing us from running them in parallel in the meantime.)

**Comment by Shadowfiend** [comment]
Obviously we moved to the ML to discuss this, but wanted to mention Diego—good point, and thanks for bringing it up/shifting the conversation back there :)

**Pull request closed without merging**
