### PR TITLE
Handle apple vcards - Issue #1790 

### PR DESCRIPTION
**Pull request by themillhousegroup**
https://github.com/lift/framework/issues/1790

As discussed at:
https://groups.google.com/forum/#!topic/liftweb/70HfjO8XWHk

### CODE REVIEW

**Comment by Shadowfiend** [comment]
Would you imagine that this would break any existing vcards being parsed?

**Comment by themillhousegroup** [comment]
I doubt it very much. All existing tests passed.

**Comment by Shadowfiend** [comment]
Ok, I'm good to merge this but you have contributor pushing to the branch disabled and there's a merge conflict. If you turn on contributor push I can fix the merge conflict, or you can; either way, I can merge after that.

**Comment by farmdawgnation** [comment]
@themillhousegroup Hi there, we would love to include this but as @Shadowfiend there's a merge conflict and we don't have access to resolve it to merge unless you give it to us. We could, of course, recreate the commits elsewhere but we don't really want to have to. :)

**Comment by farmdawgnation** [comment]
@Shadowfiend @themillhousegroup Merged this manually. Thanks for the contribution!

**Comment by Shadowfiend** [comment]
:100: nice!

**Pull request merged**
