### PR TITLE
WIP: Vanilla JS Artifacts

### PR DESCRIPTION
**Pull request by Bhashit**
Addresses #1840.  Added a basic structure. A partial first pass. Not tested yet. Still working on it.

### CODE REVIEW

**Comment by farmdawgnation** [comment]
@Bhashit Hey, friendly reminder that we're cutting an RC on Friday. If you think it's reasonable to have it done by then and can do it - then go for it. If that's not reasonable we'll slate it for 3.3 :)

Thanks for your work on this!

**Comment by Bhashit** [comment]
@farmdawgnation Yeah,I have been feeling guilty for weeks for not completing this. I'm planning to take some time out and finish this and another ticket this week.

**Comment by farmdawgnation** [comment]
Didn't mean to make you feel guilty. Please don't stress over it. :)

**Comment by farmdawgnation** [comment]
Hey there, I'm closing PR as orphaned since it's been more than a year since it's had any updates. Feel free to reopen when you have time to update it!

**Pull request closed without merging**
