### PR TITLE
Bump sbt and Scala 2.12/13 minor versions

### PR DESCRIPTION
**Pull request by Shadowfiend**
Hopefully Travis agrees with us here.

### CODE REVIEW

**Comment by farmdawgnation** [comment]
Was this intentionally opened as a draft?

**Comment by Shadowfiend** [comment]
Yah I wanted to smash it if I had Travis build issues. But it looks like it worked 🎉

**Comment by Shadowfiend** [comment]
2.12 build is still using .9 in Travis though...

**Comment by Shadowfiend** [comment]
This is ready to go I think. Tweaked the Travis config to use the right versions on the cross JVM builds also and everything looks good. Will merge tomorrow if no objections surfaced.

**Pull request merged**
