### PR TITLE
 Publishable by Travis

### PR DESCRIPTION
**Pull request by farmdawgnation**
More detailed description incoming, but we're working on moving our publishing build to Travis.

### CODE REVIEW

**Comment by Shadowfiend** [comment]
Oh mannnn das so greeeeeeen!

**Comment by farmdawgnation** [comment]
Yeah unfortunately it didn't actually publish anything afaict

**Comment by Shadowfiend** [comment]
```
[info] 	published lift-webkit_2.11 to https://oss.sonatype.org/content/repositories/snapshots/net/liftweb/lift-webkit_2.11/3.0-SNAPSHOT/lift-webkit_2.11-3.0-SNAPSHOT.pom
[info] 	published lift-webkit_2.11 to https://oss.sonatype.org/content/repositories/snapshots/net/liftweb/lift-webkit_2.11/3.0-SNAPSHOT/lift-webkit_2.11-3.0-SNAPSHOT.jar
[info] 	published lift-webkit_2.11 to https://oss.sonatype.org/content/repositories/snapshots/net/liftweb/lift-webkit_2.11/3.0-SNAPSHOT/lift-webkit_2.11-3.0-SNAPSHOT-sources.jar
[info] 	published lift-webkit_2.11 to https://oss.sonatype.org/content/repositories/snapshots/net/liftweb/lift-webkit_2.11/3.0-SNAPSHOT/lift-webkit_2.11-3.0-SNAPSHOT-javadoc.jar
```

:tada::tada::tada::tada:

**Comment by farmdawgnation** [comment]
:tada: Let's do it!!!

**Pull request merged**
