### PR TITLE
Convert \\ to return a JObject

### LINKED ISSUE #1518: Inconsistency when querying over JSON lists
Consider:

```scala
import net.liftweb.json._
import net.liftweb.json.JsonDSL._

object JsonTest extends App {
  val json =
    ("people" -> List(
      ("person" ->
        ("name" -> "Joe") ~
        ("age" -> 35)
      ),
      ("person" ->
        ("name" -> "Marilyn") ~
        ("age" -> 33)
      ),
      ("person" ->
        ("name" -> "Erik") ~
        ("age" -> 28)
      )))

  val names = (json \\ "name").children map { case JField(_, JString(name)) => name }
  println(names) // List("Joe", "Marilyn", "Erik")   -- as expected

  val json2 =
    ("people" -> List(
      ("person" ->
        ("name" -> "Joe") ~
        ("age" -> 35)
      )))

  val names2 = (json2 \\ "name").children map { case JField(_, JString(name)) => name }
  println(names2)  // List()   -- expecting List("Joe")

  val json3 =
    ("people" -> List[(String, JObject)]())

  val names3 = (json3 \\ "name").children map { case JField(_, JString(name)) => name }
  println(names3)  // List()   -- as expected
}
```

...is it by design that the `json2` case doesn't work as expected?

### PR DESCRIPTION
**Pull request by farmdawgnation**
This PR closes #1518.

I tried to be clever in an earlier implementation of this by leaving the old version in place. Unfortunately, doing so proved tricker than I'd have liked with the compiler. So unless someone comes up with Clever Ideas™ or manages to make it work, this is my proposed solution. :)

Until now, \\ returned a JValue, and could vary between returning
the value inside a field or a JObject with multiple matching values
depending on what was matched. This led to inconsistencies in the
API and unpredictable inconsistencies for the consumer of the API
(typically, if there was only one field that matched, you would get the
field's value, while multiple fields would produce a JObject with the
matching fields).

We now always return a JObject, and never return a matching field's
value directly.

### CODE REVIEW

**Comment by joescii** [comment]
I don't follow why the return type needs to change.  In issue #1518, the samples show the use of `.children` which is where the `JField` type comes into play.

**Comment by farmdawgnation** [comment]
I suppose could wrap the result into a `JObject` instead of just returning a raw `List[JField]`, then we'd be able to use the `JValue` return type. Is that's preferable here?

**Comment by farmdawgnation** [comment]
Hmm. Yeah, I can see how that would be better... I'll change it.

**Comment by joescii** [comment]
Give that a shot and I'll take a look.  I'm still tinkering with the original example given in the issue to get it fully loaded into working memory. :)

**Comment by farmdawgnation** [comment]
Oh, okay, so I remembered why I thought this would be a good idea.

This change significantly changes the behavior of the function. Changing the return type will actually break compiles instead of silently breaking matches. So, we can set the return type to `JObject` or we can set it to `List[JField]` - but if we leave it as `JValue` the compiler won't provide any help toward isolating places where the behavior will have changed.

**Comment by joescii** [comment]
Ah, I see your point.  So... Apparently we've changed something already in the types because the code in the issue doesn't compile against master.  I couldn't quite figure out what was going on until I pasted it into a test to find out that things indeed didn't line up.

**Comment by farmdawgnation** [comment]
Yeah JField is no longer a JValue. That's probably why. 

I think List[JField] is the right answer here because of how this method tends to be used. It tends to be used as a find instead of a filter. At least IME.

**Comment by joescii** [comment]
Ah, ok.  And it makes a lot of sense that `JField` would NOT be a `JValue` anyway.  

While I understand the motivation to prefer a compilation-breaking change over a behavior-breaking change, why should we go with `JField` in particular rather than `List[JValue]`?  The `name` will always match `nameToFind` in `\\`.

**Comment by farmdawgnation** [comment]
Hm. Good point. Can you raise that question on the list?

**Comment by farmdawgnation** [comment]
I'm currently out and will probably forget.

**Comment by joescii** [comment]
Thread updated :+1:

**Comment by farmdawgnation** [comment]
Alright, per the thread I'm changing this to return a JObject. :tada:

**Comment by joescii** [comment]
:+1:

**Comment by Shadowfiend** [comment]
:+1: from me as well, let's get 'er in!

**Comment by Shadowfiend** [comment]
Can we make sure the lift-json README is up-to-date as well? In particular, can we double-check that the examples involving `\\` are still correct?

**Comment by farmdawgnation** [comment]
I laugh at your entirely fair recommendation. And then agree to do it.

**Comment by Shadowfiend** [comment]
Lol. Yeah, I was going to merge this last night as the last thing I was going to do, and then I remembered :(

**Comment by farmdawgnation** [comment]
README will need some updates. I'll try to get around to that today.

**Comment by farmdawgnation** [comment]
Okay, so I was wrong. README and such are fine it seems. I did nuke some whitespace tho.

**Comment by Shadowfiend** [comment]
Nailed it! I'm :+1: here if you consider everything ready to go then :)

**Comment by farmdawgnation** [comment]
Let's do it.

**Pull request merged**
