### PR TITLE
Json serialization any

### PR DESCRIPTION
**Pull request by joescii**
This should be an easy code review.  It just opens up the json serialization to take `Any` rather than restricting the input to `AnyRef`.  Relevant ML thread [here](https://groups.google.com/forum/#!topic/liftweb/imOBZ3W6vjM).

### CODE REVIEW

**Comment by joescii** [comment]
Well, I said it would be easy but looks like there may be some merge conflicts? Or is it just travis complaining?

**Comment by farmdawgnation** [comment]
There are merge conflicts. My work probably crossed hairs with yours. :/

**Comment by joescii** [comment]
Bah.  I'll pull master and see if I can get it merged.

**Comment by joescii** [comment]
Ah, ok. It's trivial. :+1:

**Comment by farmdawgnation** [comment]
Let's do it.

**Pull request merged**
