### PR TITLE
Segmented Thinking: Change how we test segment size changes.

### LINKED ISSUE #1820: net.liftweb.json.XmlExamples failing in Scala 2.12 community build
seen at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1080/consoleFull and https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1081/consoleFull

failing commit is 79d036703eedf32a27485574ded1bf2805421ead

last green commit 16f61a0c8d3f647188b0978456e47fc18ecc7293

```
[lift-json] [info] XML Examples
[lift-json] [info] 
[lift-json] [info] + Basic conversion example
[lift-json] [info] + Conversion transformation example 1
[lift-json] [info] + Conversion transformation example 2
[lift-json] [info] + Primitive array example
[lift-json] [info] + Lotto example which flattens number arrays into encoded string arrays
[lift-json] [error] x Band example with namespaces
[lift-json] [error]  'JObject(List(JField(b:band,JObject(List(JField(name,JString(The Fall)), JField(genre,JString(rock)), JField(influence,JString()), JField(playlists,JObject(List(JField(playlist,JArray(List(JObject(List(JField(name,JString(hits)), JField(song,JArray(List(JString(Hit the north), JString(Victoria)))))), JObject(List(JField(name,JString(mid 80s)), JField(song,JArray(List(JString(Eat your self fitter), JString(My new house)))))))))))))))))'
[lift-json] [error]  
[lift-json] [error]   is not equal to 
[lift-json] [error]  
[lift-json] [error]  'JObject(List(JField(b:band,JObject(List(JField(name,JString(The Fall)), JField(genre,JString(rock)), JField(influence,JString()), JField(playlists,JObject(List(JField(playlist,JArray(List(JObject(List(JField(name,JString(hits)), JField(song,JArray(List(JString(Hit the north), JString(Victoria)))))), JObject(List(JField(name,JString(mid 80s)), JField(song,JArray(List(JString(Eat your self fitter), JString(My new house)))))))))))))))))' (XmlExamples.scala:80)
[lift-json] [error] Actual:   ...(rock[)), JField(influence,JString()), JField(playlists,JObject(List(JField(playlist,JArray(List(JObject(List]
[lift-json] [error] [(JField(name,JString(hits)), JField(song,JArray(List(JString(Hit the north), JString(Victoria)))))), JObject(List(JField(name,JString(mid 80s)), JField(song,JArray(List(JString(Eat your self fitter), ]
[lift-json] [error] [JString(My new house)))))))))))))))))]
[lift-json] [error] Expected: ...(rock[]
[lift-json] [error] []
[lift-json] [error] []
[lift-json] [info] 
```

in the community build, I will freeze at 16f61a0c8d3f647188b0978456e47fc18ecc7293 for now

### PR DESCRIPTION
**Pull request by Shadowfiend**
We were testing segment size changes by using mutable state on a global
Segments singleton. With the new parsing approach, which aggressively
uses mutability to increase performance, this was causing derivative
concurrency failures in many places.

We now change the way to test different segment sizes by putting an
interface in front of the segment pool and allowing it to be customized
on a per-Buffer basis, and making the spec instantiate the Buffer with
a different segment pool while testing.

This functionality is currently still entirely private in the json
package, but can be exposed in the future if we deem it useful. For
now, its sole purpose is to confirm that buffer size can be changed
without adverse effects.

I believe this should fix #1820, and it should fix the travis failures
we're currently seeing as well.

For an extra layer of confidence, please run `lift-json/test` a few times
locally and make sure you aren't seeing failures, as well as giving the
full `test` an opportunity to run and make sure there are no lift-json
failures.

### CODE REVIEW

**Comment by farmdawgnation** [comment]
Oh lordy. Thank you for finding this, I could never get a failure locally. >_>

**Comment by farmdawgnation** [comment]
Do we need to worry about the shared singleton in the main parsing code?

**Comment by Shadowfiend** [comment]
No, that is unchanged, and that singleton no longer has externally-accessible mutable state (the segment size was the only piece of externally-accessible mutable state, and it was private to the `json` package for test purposes; it's now straight up immutable). All remaining mutable state is managed through threadsafe APIs. Additionally, the specs test concurrent use of the parser---which is why we were seeing these issues.

**Comment by farmdawgnation** [comment]
AHHHHHHH, alright then. That makes total sense.

**Comment by farmdawgnation** [comment]
Naturally, I just looked at the original test code again and realized that I was looking at the wrong bit earlier when I looked at this. ;)

**Comment by Shadowfiend** [comment]
Going to run the travis build one more time and merge if it's green.

**Comment by farmdawgnation** [comment]
It looks greeeeennnnn

**Comment by Shadowfiend** [comment]
👍

**Pull request merged**
