### PR TITLE
fixes #1658 (CombParserHelpersSpec fails when string with \n is probed)

### LINKED ISSUE #1658: CombParserHelpersSpec fails when string with \n is probed
"... provide an aNumber parser - returning an Int if succeeding" fails because "1\n" matches criteria aNumber but doesn't match regex expression "\\p{Nd}+.*". Because without DOTALL "\n" doesn't match ".*"

Link to mailing list discussion: https://groups.google.com/forum/#!topic/liftweb/hHzK9lgXyKs

Pull Request: #1659

### PR DESCRIPTION
**Pull request by arkadius**
fixes #1658

### CODE REVIEW

**Comment by Shadowfiend** [comment]
As I mentioned in the other PR, a better commit message would be ideal here. Ideally it would include the information that's listed in the issue (a short summary that indicates what changed, e.g. “Fix CombParserHelperSpec for digits with newlines.”, then a description indicating why it was failing and what you did to fix it).

**Comment by arkadius** [comment]
Done it.

**Comment by Shadowfiend** [comment]
Lovely! I'll merge this in later today after rebasing a bit so we only include the good commit :)

**Comment by Shadowfiend** [comment]
Okay, merged this via https://github.com/lift/framework/commit/f12a1d905b6aa79cfe7de6d46648c56861d667ba after making sure we only pulled the clean commit. I'll let #1664 bring in the updated contributors.md file.

**Pull request closed without merging**
