### PR TITLE
Add 'X-Requested-With' header to liftVanilla

### LINKED ISSUE #1745: Add 'X-Requested-With' header to liftVanilla
Lift checks for that header in `Req.ajax_?` to determine if the request is ajax.

### PR DESCRIPTION
**Pull request by eltimn**
Fixes #1745

### CODE REVIEW

**Comment by Shadowfiend** [comment]
This all looks pretty swell to me. :+1: though probably the one issue that Codacy identified (used `!=` instead of `!==`) could be addressed.

**Comment by eltimn** [comment]
There are a bunch of places in lift.js that codacy is still reporting issues. Although, it only seems to complain when you touch the code where the problem is.

I will add a `.jshintrc` file so jshint will pick them up better. I figured it would be better to do that as a separate commit, so it's just the formatting changes.

**Comment by Shadowfiend** [comment]
This looks 100% good to me. If you want to add `jshintrc` that's fine, but if not I'm down with that as well and happy to merge as-is.

**Comment by farmdawgnation** [comment]
:+1:

**Comment by Shadowfiend** [comment]
There's a merge conflict here, but other than that this is looking good to me.

**Comment by Shadowfiend** [comment]
Let's do eeet!

**Pull request merged**
